dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
env:
  - JAX_ENABLE_X64=0 JAX_NUM_GENERATED_CASES=100
  - JAX_ENABLE_X64=1 JAX_NUM_GENERATED_CASES=100
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
  - conda config --add channels conda-forge
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip nose six protobuf>=3.6.0 absl-py opt_einsum numpy scipy flake8
  - pip install jaxlib
  - pip install -v .
before_script:
  # fail the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
script:
  - nosetests tests examples
notifications:
  email: false
