name: "Pull Request Labeler on approval"
on:
  pull_request:
    types: [ labeled ]

jobs:
  review-approval:
    # Check the pull request review.
    if: ${{ github.event.label.name == 'pull ready' }}          
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['build']
            })
      # - name: Simple Issue Labeler
      #   uses: andymckay/labeler@1.0.2
      #   with:
      #     add-labels: "build"
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}