name: Add label on approval
on:
  repository_dispatch:
    # From: pull_request_review
    types: [created, edited, submitted]

jobs:
  review-approval:
    # Check the pull request review.
    if: >-
      ${{ github.actor == 'tfdocsbot' &&
          contains(github.event.client_payload.review.state, 'approved') }}
    runs-on: ubuntu-latest
    steps:
    - name: Add label
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_URL: ${{ github.event.client_payload.pull_request.issue_url }}
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          "${ISSUE_URL}/labels" \
          --data '{"labels":["kokoro:run"]}'