name: Continuous integration

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build/test-requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Type check with mypy
      run: |
        mypy jax

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - python-version: 3.6
            os: macos-latest
            enable-x64: disable-x64
            num_generated_cases: 10
          - python-version: 3.7
            os: ubuntu-latest
            enable-x64: enable-x64
            num_generated_cases: 25
          - python-version: 3.7
            os: ubuntu-latest
            enable-x64: enable-x64
            num_generated_cases: 25
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build/test-requirements.txt
    - name: Run tests
      run: |
        pip install -e .
        [ ${{ matrix.enable-x64 }} = enable-x64 ] && JAX_ENABLE_X64=1 || JAX_ENABLE_X64=0 
        export JAX_NUM_GENERATED_CASES=${{ matrix.num_generated_cases }}
        echo "JAX_NUM_GENERATED_CASES=$JAX_NUM_GENERATED_CASES"
        echo "JAX_ENABLE_X64=$JAX_ENABLE_X64"
        if [ $JAX_ENABLE_X64 = 0 ]; then
          pytest -n auto jax/experimental/jax2tf/tests
        fi
        pytest -n auto tests examples


  documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt install -y pandoc
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
    - name: Build and test documentation
      run: |
        sphinx-build -b html -D nbsphinx_execute=always docs docs/build/html
        pytest docs
        pytest --doctest-modules jax/api.py

