name: Wheel build - Windows CPU x86_64
on:
  workflow_dispatch: # allows triggering the workflow run manually

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  DISTUTILS_USE_SDK: 1
  MSSdk: 1

jobs:
  win-wheels:
    strategy:
      fail-fast: false  # Don't stop all wheel builds if one has a test failure.
      matrix:
        os: [windows-2019-32core]
        arch: [AMD64]
        pyver: ['3.10', '3.11', '3.12', '3.13.0-rc.2']
    name: ${{ matrix.os }} ${{ matrix.pyver }} jaxlib wheel build
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install LLVM/Clang
        run: choco install llvm --version=18.1.4 --yes --no-progress --allow-downgrade

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # v4.1.1

      - uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3  # v5.2.0
        with:
          python-version: ${{ matrix.pyver }}
          cache: 'pip'

      - name: Build wheels
        env:
          BAZEL_VC: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC"
          JAXLIB_RELEASE: true
        run: |
          python -m pip install -r build/test-requirements.txt
          python -m pip install --upgrade numpy==2.0.0 scipy==1.13.1
          "C:\\msys64\\;C:\\msys64\\usr\\bin\\;" >> $env:GITHUB_PATH
          python.exe build\build.py `
            --bazel_options=--color=yes `
            --bazel_options=--config=win_clang `
            --verbose

      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874  # v4.4.0
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.pyver }}
          path: ${{ github.workspace }}\dist\*.whl
          retention-days: 5

      - name: Run tests
        env:
          JAX_ENABLE_CHECKS: true
          JAX_SKIP_SLOW_TESTS: true
          PY_COLORS: 1
        run: |
          python -m pip install --find-links ${{ github.workspace }}\dist jaxlib
          python -m pip install -e ${{ github.workspace }}
          echo "JAX_ENABLE_CHECKS=$JAX_ENABLE_CHECKS"
          pytest -n auto --tb=short tests examples
